version: '3.1'

services:
  mongodb:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - './data:/data/db'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
  mongo-ui:
    container_name: mongo-ui
    image: mongo-express
    restart: always
    ports:
      - "8090:8081"
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME : ${MONGODB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD  : ${MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
