spring:
  data:
    mongodb:
      uri: mongodb://palmetto_user:palmetto123@mongodb:27017
      database: mongodb
  cloud:
    function:
      definition: orderProducer;notificationConsumer
    stream:
      kafka:
        binder:
          brokers: kafka:9091
          autoCreateTopics: false
      bindings:
        orderProducer-out-0:
          destination: orders
        notificationConsumer-in-0:
          destination: notifications
          consumer:
            partitioned: true
            concurrency: 3
          group: client-notification-in

server:
  port: 8080
