spring:
  cloud:
    function:
      definition: notificationProducer;orderConsumer
    stream:
      kafka:
        binder:
          brokers: kafka:9091
          autoCreateTopics: false
      bindings:
        notificationProducer-out-0:
          destination: notifications
        orderConsumer-in-0:
          destination: orders
          consumer:
            partitioned: true
            concurrency: 3
          group: palmetto-order-in

server:
  port: 8080
