spring:
  cloud:
    function:
      definition: notificationSender;notificationListener
    stream:
      kafka:
        binder:
          brokers: kafka:9091
          autoCreateTopics: false
      bindings:
        notificationSender-out-0:
          destination: notifications
        notificationListener-in-0:
          destination: notifications
          consumer:
            partitioned: true
            concurrency: 3
          group: courier-notification-in

server:
  port: 8080
