spring:
  cloud:
    function:
      definition: notificationProducer;notificationConsumer
    stream:
      kafka:
        binder:
          brokers: kafka:9091
          autoCreateTopics: false
        bindings:
          notificationConsumer-in-0:
            consumer:
              ackMode: COUNT
              autoCommitOffset: false
              autoCommitOnError: false
      bindings:
        notificationProducer-out-0:
          destination: notifications
        notificationConsumer-in-0:
          destination: notifications
          consumer:
            partitioned: true
            concurrency: 3
          group: courier-notification-in

server:
  port: 8080
